MovieApp/Models/Category.cs
namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MovieApp/Models/Movie.cs
namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ShortDescription { get; set; }

        public string Description { get; set; }

        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }
    }
}

MovieApp/Models/MovieCategoryModel.cs
using System.Collections.Generic;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Category> Categories { get; set; }

        public IEnumerable<Movie> Movies { get; set; }
    }
}

MovieApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models;
using MovieApp.Data;
using System.Linq;

namespace MovieApp.Controllers
{
    public class HomeController:Controller
    {
        

        [HttpGet]
        //Home/Index/3
        //Home/Index
        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.Movies;

            if(id!=null)
            {
             movies = movies.Where(i => i.CategoryId == id).ToList();
            }
        
          

            return View(movies);
        }
        public IActionResult Details(int id){

            // MovieCategoryModel model = new MovieCategoryModel();
            // model.Categories=CategoryRepository.Categoryies;
            // model.Movie=MovieRepository.GetById(id);

            return View(MovieRepository.GetById(id));
        }
        public IActionResult Contact()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }


    }
}

MovieApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController:Controller
    {
        public IActionResult Index()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        
        public IActionResult Create()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult Details()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }

        public IActionResult List()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
    }
}

MovieApp/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;

namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if(RouteData.Values["action"].ToString()=="Index")
                ViewBag.SelectedCategory =RouteData?.Values["id"];

            return View(CategoryRepository.Categoryies);
        }
        
    }
}

MovieApp/Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

MovieApp/Views/Home/Details.cshtml
@model Movie
<div class="row">
    <div class="col-md-3">
        <!-- Html.Partial("_menu",Model.Categories) -->
        @await Component.InvokeAsync("CategoryMenu")
    </div>

<div class="col-md-9">
    <div class="card-body">
        <div class="row no-gutter">
            
    
                <div class="col-md-4">
                    <img src="~/img/@Model.ImageUrl" alt="" class="card-img">
                </div>

                <div class="col-md-8">
                    <h5 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id">
                            @Model.Name
                        </a>
                    </h5>
                    <p class="card-text">
                        @Html.Raw(Model.Description)
                    </p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>
        </div>
    </div>
</div>

MovieApp/Views/Home/Index.cshtml
@model IEnumerable<Movie>



<div class="row">
    <div class="col-md-3">
        <!--Html.Partial("_menu",Model.Categories)-->
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
         @Html.Partial("_movies",Model) 
        <!--<partial name="_movies" model="Model.Movies">-->
    </div>
</div>

MovieApp/Views/Home/_movies.cshtml
@model IEnumerable<Movie>
@foreach (var movie in Model)
{
    <div class="card mb-3">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="~/img/@movie.ImageUrl" alt="" class="card-img">
            </div>

            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@movie.Id">
                            @movie.Name
                         </a>
                    </h5>
                    <p class="card-text">
                        @movie.ShortDescription
                    </p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>

                </div>
            </div>
        </div>
    </div>
}

MovieApp/Views/Movie/Details.cshtml
<h1>Movie/Details</h1>

MovieApp/Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

MovieApp/Views/Movie/List.cshtml
<h1>Movie/List</h1>

MovieApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">

        <a href="/"class="list-gro-item list-group-item">Tüm Kategoriler</a>

    @foreach (var i in Model)
    {

        <a  asp-controller="Home" asp-action="Index" asp-route-id="@i.Id"
        class="list-gro-item list-group-item 
        @(ViewBag.SelectedCategory==i.Id.ToString()? "active":"")">
        @i.Name
        </a>
    }

</div>

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <title>Document</title>
</head>
<body>
    <header>
        @Html.Partial("_header")
    </header>
    <main>
        <div class="container mt-4"> 
            @RenderBody()
        </div>
    </main>

    <footer>
        @Html.Partial("_footer")
    </footer>

    @RenderBody()

</body>
</html>

MovieApp/Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            Place footer content here.
        </span>
    </div>
</div>

MovieApp/Views/Shared/_header.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
              <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>

MovieApp/Views/Shared/_menu.cshtml
@model IEnumerable<Category>

@foreach (var i in Model)
{
    <div class="list-group">
        <a href="" class="list-gro-item list-group-item">@i.Name</a>

    </div>
}